### PR TITLE
Fix compilation warnings with gcc-12

### PR DESCRIPTION
**Pull request by jcheng5**
Requested by CRAN.

### CODE REVIEW

**Comment by jcheng5** [comment]
Tested with this dockerfile:

```
FROM rocker/r-edge:gcc-12

RUN apt-get -y update
RUN apt-get -y install git
RUN R --slave -e "install.packages('knitr')"
RUN R --slave -e "install.packages('sass')"
RUN apt-get -y install libcurl4-openssl-dev
RUN R --slave -e "install.packages(c('testthat', 'rmarkdown', 'withr', 'shiny', 'curl'))"
RUN apt-get -y install pandoc
RUN mkdir /root/.R
RUN echo "CFLAGS +=              -O3 -Wall -pipe -pedantic -std=gnu99" > /root/.R/Makevars
RUN echo "CXXFLAGS +=            -O3 -Wall -pipe -Wno-unused -pedantic" >> /root/.R/Makevars

# git clone https://github.com/rstudio/sass && R CMD build --no-build-vignettes --no-manual sass && R CMD check sass*.tar.gz
```

**Review by wch — APPROVED** [review]
Looks good!

It's strange that CRAN has decided to treat this warning as significant, but I guess we just have to deal with it.

**Comment by jcheng5** [comment]
@wch @schloerke Any idea about the GHA failures? Especially the R 3.6/Windows one?

**Comment by schloerke** [comment]
Windows is a "make can't find file". I've not seen that error before. Don't know why the compilation isn't happening.

The pkgdown error is failing with feature request GitHub file. Did something change or is it malformed?

**Comment by cpsievert** [comment]
Merging since [4810f8d](https://github.com/rstudio/sass/pull/100/commits/4810f8dd3d059f72f4f9e86a673c4251b93d2395) fixes the pkgdown error and I don't think Win 3.6 has ever passed for sass because of Make no being included in RTools for some reason

**Pull request merged**
